import subprocess
from pathlib import Path
import shutil
import os
import zipfile

def pdf_to_png(input_paths, output_path):
    """Convert a PDF file to a series of PNG images packaged in a ZIP file."""
    if not input_paths:
        return
    input_pdf = input_paths[0]
    
    # Create a temporary directory for output PNGs
    temp_dir = output_path.parent / "temp_pngs"
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    prefix = temp_dir / "page"
    
    try:
        # Execute pdftoppm to output png files
        subprocess.run(
            ["pdftoppm", "-png", "-r", "144", str(input_pdf), str(prefix)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
    except Exception as e:
        # Clean up temp dir
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise RuntimeError(f"pdftoppm failed: {e}")
        
    png_files = sorted(temp_dir.glob("page-*.png"))
    if not png_files:
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise RuntimeError("No PNG pages were generated by pdftoppm")
        
    # Write files to ZIP
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for png_file in png_files:
            zip_file.write(png_file, png_file.name)
            
    # Cleanup temp directory
    shutil.rmtree(temp_dir, ignore_errors=True)
    print(f"Exported PDF pages to PNG zip: {output_path}")
