server {
    listen 80;
    listen [::]:80;
    server_name pdfmount.online www.pdfmount.online;
    root /opt/pdfmount/dist;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
